apiVersion: apps/v1
kind: Deployment
metadata:
  name: jovies-app
  labels:
    environment: production
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: jovies-app
          resources:
            requests:
              memory: "40Mi"
              cpu: "15m"
            limits:
              memory: "100Mi"
              cpu: "50m"
