apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies

resources:
  - ../../base
  - resourcequota.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jovies
    newTag: main-sha-774fefa0817701ece946b3d562332a075a284849

patchesStrategicMerge:
  - deployment-patch.yaml
