apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies

resources:
  - ../../base
  - resourcequota.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jovies
    newTag: main-sha-f5ec1629d459aa55abe8d408e48d75dbbc9f62fd

patchesStrategicMerge:
  - deployment-patch.yaml
