apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies

resources:
  - ../../base
  - resourcequota.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jovies
    newTag: main-sha-abc9dc71e18d0f337e5fc07499c8b447336b16e4

patchesStrategicMerge:
  - deployment-patch.yaml
