apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies

resources:
  - ../../base
  - resourcequota.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jovies
    newTag: main-sha-69b3fc9deb45c82ac19120458829d940f1f7a498

patchesStrategicMerge:
  - deployment-patch.yaml
