apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies

resources:
  - ../../base
  - resourcequota.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jovies
    newTag: main-sha-5b5e3655087f903b8908822cf130714325aede53

patchesStrategicMerge:
  - deployment-patch.yaml
