apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies

resources:
  - ../../base
  - resourcequota.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jovies
    newTag: main-sha-a1729a14cc8e68a86f1e2cea013acd005521f21f

patchesStrategicMerge:
  - deployment-patch.yaml
