apiVersion: v1
kind: ResourceQuota
metadata:
  name: jovies-quota
  namespace: jovies
spec:
  hard:
    requests.memory: "200Mi"
    requests.cpu: "100m"
    limits.memory: "400Mi"
    limits.cpu: "200m"
    pods: "9"
