apiVersion: v1
kind: ResourceQuota
metadata:
  name: jovies-quota
  namespace: jovies
spec:
  hard:
    requests.memory: "600Mi"
    requests.cpu: "600m"
    limits.memory: "900Mi"
    limits.cpu: "1200m"
    pods: "9"
