apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: github.com/Mayne0213/jovies
    newTag: develop-sha-bed2d09069c0a4a2f83dfd74a8489dcf67625a7d

patchesStrategicMerge:
  - deployment-patch.yaml
