apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/jovies
    newTag: develop-sha-be509a4f6033c6c3055517bf0266e5c46d52490e

patchesStrategicMerge:
  - deployment-patch.yaml
