apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jovies
    newTag: develop-sha-b27f4a1c67210ae1b2d1096e35c19c70258d9a66

patchesStrategicMerge:
  - deployment-patch.yaml
