apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jovies
    newTag: develop-sha-422977ae47ad6f57aea541d216758d888e589314

patchesStrategicMerge:
  - deployment-patch.yaml
