apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jovies
    newTag: develop-sha-cac7c5c510824413abd3c5efd22dbe434b1a83d9

patchesStrategicMerge:
  - deployment-patch.yaml
