apiVersion: v1
kind: ResourceQuota
metadata:
  name: jovies-dev-quota
  namespace: jovies-dev
spec:
  hard:
    requests.memory: "150Mi"
    requests.cpu: "50m"
    limits.memory: "300Mi"
    pods: "6"
